<?php
return[
    [
        "img"=>"images/footer-facebook.png",
        "link"=>"https://facebook.com"
    ],
    [
        "img"=>"images/footer-twitter.png",
        "link"=>"https://twitter.com"
    ],
    [
        "img"=>"images/footer-youtube.png",
        "link"=>"https://youtube.com"
    ],
    [
        "img"=>"images/footer-pinterest.png",
        "link"=>"https://pinterest.com"
    ],
    [
        "img"=>"images/footer-periscope.png",
        "link"=>"https://periscope.com"
    ],

]
?>
